### ISSUE TITLE
0.1.2 - broken ?

### ISSUE THREAD

**Issue by Krecik7** [stefanor/signalk-victron-ble#18]
After update & restart

Nov 29 15:17:41 Plugin exited 1, restarting...
Nov 29 15:17:42 File "/home/signalk/.signalk/node_modules/.pnpm/signalk-victron-ble@0.1.2/node_modules/signalk-victron-ble/plugin.py", line 395 "value": data.get_yield_today() * 3600, // SignalK expects Joules ^ SyntaxError: invalid syntax

**Comment by stefanor** [comment]
@Krecik7: The unit of yieldToday is Joules, not kwH. That's why the multiplier.
