### ISSUE TITLE
Add support for Solar Power on MPPT

### ISSUE THREAD

**Issue by steveuk71** [stefanor/signalk-victron-ble#4]
Following fields available to report, the current Solar Input Watts and Total Yield Watts today    

"model_name": "SmartSolar MPPT 75|15",

    "solar_power": 0,

    "yield_today": 20

**Comment by stefanor** [comment]
I'm afraid there aren't defined keys for either of these in the SignalK spec: https://signalk.org/specification/1.7.0/doc/vesselsBranch.html

The first step would be to define them in https://github.com/SignalK/specification

**Comment by stefanor** [comment]
You can, of course, calculate both of these from existing values. Power = Voltage * Current, and yield today is Power since midnight.

**Comment by stefanor** [comment]
`panelPower` is added in #6

**Comment by stefanor** [comment]
Filed SignalK/specification#653 for the specification updates.

**Comment by tkurki** [comment]
Just to make sure you know: the SK server is schema agnostic, you can basically invent your own paths. Naturally if the name of the path is obvious / noncontroversial we should pretty quickly add it to the specifiation. The main advantags are that then you get unit information from the schema and various pieces of software use the same path for the same thing.

But you *can* start using any path and SK server will work.
